### ISSUE TITLE
Services don't persist after restart

### ISSUE THREAD

**Issue by DiedvD** [DanielGiljam/homebridge-nexa-switch-platform#2]
When restarting homebridge, the switches do not work anymore from Homekit if they are loaded from the Homebridge cache.

I suspect that the services added to the accessories on registering do not get cached along with the accessory info but rather that they have to be re-initialized. See the note at https://github.com/nfarina/homebridge/blob/5a5a1b5f2dd31c1bce62858e57967723772df6dd/example-plugins/homebridge-samplePlatform/index.js#L68 (however I am not yet that experienced with Homebridge).

Would need to add the logic for the switch service to the configureAccessory function. In contrast to the registry function, can't loop over the accessory index. Hence we might want to add another option to the accessory config that specifies the group code (instead of accessoryIndex), also giving more flexibility to end-user. (Which would also fix another issue of mine that the group codes are off by one due to the +1 at https://github.com/DanielGiljam/homebridge-nexa-switch-platform/blob/0e50597b144fd55434a9f192490e809ab295c02a/index.js#L91 )

I am willing and going to propose a fix myself but thought it wise to open an issue for clarity anyways.

Reference for grouping codes http://homeeasyhacking.wikia.com/wiki/Advanced_Protocol

**Comment by DanielGiljam** [comment]
Thanks for your fix and the other improvements!
